### ISSUE TITLE
标题格式是不是有问题？

### ISSUE THREAD

**Issue by zzqxztc** [DansYU/SeuThesiY#3]
我看其他的模板里。
二级标题 节 的字体是加粗 宋体
三级标题 小节 的字体是黑体

我看东南大学的学位论文格式要求好像也是这样。

这边貌似 二级标题 是加粗的黑体？
三级标题 字体有点大 也不是黑体

**Comment by DansYU** [comment]
这个模板是在[seuthesix](https://github.com/zhimengfan1990/seuthesix)的基础上修改的
学校的要求是这样的：
（2）一级标题（题目）：二号宋体居中；二级标题（章）：三号黑体居中。
（3）三级标题（节）：四号宋体（加粗）居左；四级标题（节内小节）小四号黑体居左。

可以修改配置文件的 Line 115 ~116
```
    subsection/format=\sihao\mdseries\raggedright,

    subsubsection/format=\sihao\mdseries\raggedright,
```

修改后合并过来 谢谢支持

**Comment by zzqxztc** [comment]
> 这个模板是在[seuthesix](https://github.com/zhimengfan1990/seuthesix)的基础上修改的 学校的要求是这样的： （2）一级标题（题目）：二号宋体居中；二级标题（章）：三号黑体居中。 （3）三级标题（节）：四号宋体（加粗）居左；四级标题（节内小节）小四号黑体居左。
> 
> 可以修改配置文件的 Line 115 ~116
> 
> ```
>     subsection/format=\sihao\mdseries\raggedright,
> 
>     subsubsection/format=\sihao\mdseries\raggedright,
> ```
> 
> 修改后合并过来 谢谢支持

好的。感谢回复。cls文件我看了下，可能是你把bfseries覆写了。我在tex文件里textbf发现宋体会自动变成加粗黑体。
你的模板主要在我的环境下，biber的biblatex编译正常。感觉中英文献都符合学校的规范。其他的好多模板也是继承的[seuthesix](https://github.com/zhimengfan1990/seuthesix)，但不知道怎么回事，bibtex的格式都不太正常😂。文献格式根本不符合学校的要求。

**Comment by zzqxztc** [comment]
> 这个模板是在[seuthesix](https://github.com/zhimengfan1990/seuthesix)的基础上修改的 学校的要求是这样的： （2）一级标题（题目）：二号宋体居中；二级标题（章）：三号黑体居中。 （3）三级标题（节）：四号宋体（加粗）居左；四级标题（节内小节）小四号黑体居左。
> 
> 可以修改配置文件的 Line 115 ~116
> 
> ```
>     subsection/format=\sihao\mdseries\raggedright,
> 
>     subsubsection/format=\sihao\mdseries\raggedright,
> ```
> 
> 修改后合并过来 谢谢支持

好的。感谢回复。cls文件我看了下，可能是你把bfseries覆写了。我在tex文件里textbf发现宋体会自动变成加粗黑体。
你的模板主要在我的环境下，biber的biblatex编译正常。感觉中英文献都符合学校的规范。其他的好多模板也是继承的[seuthesix](https://github.com/zhimengfan1990/seuthesix)，但不知道怎么回事，bibtex的格式都不太正常😂。文献格式根本不符合学校的要求。
